name: 'SWIGGY'
version: '1.0.0'

profile: 'SWIGGY'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  SWIGGY:
    +database: SWIGGY
    +schema: SWIGGY_STAGE
    SWIGGY_STAGE:
      +materialized: table